- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4865/workspace/Maven-AnsibleWebApp/Maven-AnsibleWebApp.war"
        dest: "/opt/tomcat/webapps/Maven-AnsibleWebApp.war"
        remote_src: no

    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted

